name: moneovoice
description: "MoneoVoice - Voice Finance App"
publish_to: 'none'
version: 1.0.9+10

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Stack Requirement: State Management
  flutter_riverpod: ^2.6.1
  
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.1
  
  # Stack Requirement: Persistence (Drift)
  drift: ^2.24.2
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Stack Requirement: Formatting & Charts
  intl: ^0.20.2
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  
  # Utilities
  equatable: ^2.0.7
  uuid: ^4.5.1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  excel: ^4.0.6
  syncfusion_flutter_xlsio: ^29.1.38
  share_plus: ^12.0.1
  dotted_border: ^2.1.0
  collection: ^1.18.0
  pdf: ^3.11.3
  printing: ^5.14.3

  # Firebase
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.0
  firebase_remote_config: ^5.4.0

  # Version check
  package_info_plus: ^8.1.3
  url_launcher: ^6.3.1
  flutter_notification_listener: ^1.4.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Gen for Drift
  drift_dev: ^2.24.2
  build_runner: ^2.4.14

  # App icon generator
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/


